CREATE TABLE CUSTOMERS(
	ID SERIAL NOT NULL PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(100),
	TC_NUMBER VARCHAR(11),
	GENDER VARCHAR(1),
	EMAIL VARCHAR(100),
	BIRTHDATE DATE,
	CITY_ID INT,
	DISTRICT_ID INT,
	TELNR1 VARCHAR(15),
	TELNR2 VARCHAR(15)
);


CREATE TABLE CITIES(
	ID SERIAL NOT NULL PRIMARY KEY,
	CITY VARCHAR(50)
);

CREATE TABLE DISTRICTS(
	ID SERIAL NOT NULL PRIMARY KEY,
	CITY_ID INT,
	DISTRICT VARCHAR(50)
);